### ISSUE TITLE
加滤镜生成视频文件大了一倍

### ISSUE THREAD

**Issue by huishuyi** [wysaid/ios-gpuimage-plus#10]
videoFrameRecorder选择不压缩和高质量压缩，视频由3M变为6.7M，加了一倍多，中等质量压缩又减小到980k又小了三分之一，之前导出过美拍的视频，加完滤镜视频后大小和加之前类似，能否实现？

**Comment by huishuyi** [comment]
能不能相对精确地控制压缩率

**Comment by wysaid** [comment]
这类问题， 你应该使用本repo的方法生成最清晰（大概最大）的视频文件， 然后自己用 avfoundation 处理成你自己能接受的（自己平衡大小和清晰度）， 我这里不会帮你完成你的精细需求

**Comment by huishuyi** [comment]
非常感谢你对我的帮助，本世纪最后一个问题，我也想和你一样自己写滤镜，剪辑....和视频制作相关的的功能，非常想知道需要学习哪方面的知识，我看过《AVFoundation开发秘籍》，还需要哪方面的知识和书籍？

**Comment by wysaid** [comment]
写滤镜的话需要看的是OpenGL相关的东西哦~~ 你多看看OpenGLES相关的吧， 尤其是API文档: https://www.khronos.org/opengles/sdk/docs/man/
