### ISSUE TITLE
Invalid Filter Config

### ISSUE THREAD

**Issue by starlight173** [wysaid/ios-gpuimage-plus#11]
Hello,
I'm taking a look on your library. I have the problem with the filter using image texture.
For example, when I use the filter that using the late_sunset.png, the log says that:
`Invalid Filter Config @adjust lut late_sunset.png`
I did copy the late_sunset.png into the project. Anything else is good.
Could you point me if i missed anything?
Thanks so much. :)

**Comment by wysaid** [comment]
Please see the demo， there's a callback in "MainActivity". The Engine would give you the name-you-write. You have the responsible to return the combined Bitmap :
`CGENativeLibrary.setLoadImageCallback(loadImageCallback, null);`
As you're giving "late_sunset.png"
A string named "late_sunset.png" would be passed to you, and you must return an UIImage which the name pointed to.
interface prototype： 

```
public interface LoadImageCallback {
        Bitmap loadImage(String name, Object arg);
        void loadImageOK(Bitmap bmp, Object arg);
    }
```

**Comment by wysaid** [comment]
@gloryluu I'm answering wrong for the android ver, but the ios ver is the same. 

In function "viewDidLoad" of "MainViewController.m":
`cgeSetLoadImageCallback(loadImageCallback, loadImageOKCallback, nil);`

**Comment by starlight173** [comment]
God, my bad. Thanks a lot.

**Comment by wysaid** [comment]
"bad"->"fault"

**Comment by wysaid** [comment]
@gloryluu  Aha, I've mistaken you for sb else, so I answered you in CN.😁
