### ISSUE TITLE
Bitcode enable issue when archieving?

### ISSUE THREAD

**Issue by starlight173** [wysaid/ios-gpuimage-plus#12]
I got this issue when keeping Enable Bitcode = YES by default. Xcode fails and gives me this error:

```
ld: bitcode bundle could not be generated because '.../library/cge.framework/cge(cgeVideoCameraViewHandler.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think the frameworks seem to be built using -fembed-bitcode-marker instead of -fembed-bitcode.

**Comment by wysaid** [comment]
Maybe xcode is updated.
I will fix that in next ver.

**Comment by wysaid** [comment]
fixed

**Comment by starlight173** [comment]
Hello, the issue seems still there with the new build. :)
`ld: bitcode bundle could not be generated because '../libCGE/cge.framework/cge(cgeDynamicImageViewHandler.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64`

**Comment by wysaid** [comment]
Oh…… I will check that again.

**Comment by wysaid** [comment]
Why can't I see the err msg on my demo (the one just provided in the repo) ?
I've tested the demo, but everything is OK

**Comment by starlight173** [comment]
Have you tried to archive it? Take a look at this [topic](http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled) :)

**Comment by wysaid** [comment]
@gloryluu 
![http://i.imgur.com/Yc4gXkf.png](http://i.imgur.com/Yc4gXkf.png)
The demo is working well, and I can't see the error~
Maybe I'm using iPhone5s, and it's arm64 ?

**Comment by starlight173** [comment]
Which xcode you're using? Normally, this's caused by missing flag '-fembed-bitcode-marker' in xcode 7+ or '-fembed-bitcode'

Bitcode is a compile-time feature (not a link-time feature) which means that every .o file should contain an extra section called __bitcode when built with bitcode. You can confirm whether your binary is bitcode-compatible by running otool -l (my .o or .a file) | grep __LLVM.

When you build normally, Xcode adds the build flag -fembed-bitcode-marker to any clang invocation. This seems to be some sort of 'this is where bitcode would go, if bitcode was enabled' thing, and doesn't actually enable bitcode.

When you "Build & Archive", this flag is replaced by -fembed-bitcode, which really does build a Bitcode-enabled binary. That causes the issue.

Just go the Build Settings. Search for "custom compiler flags". Add -fembed-bitcode or  -fembed-bitcode-marker (depends on the xCode version) to Other C Flags. This will ensure that the lib is built with bitcode compatibility at compile time. I made this for iOS, 64 bit and 32 bit, and lipo'd them into one
ref: http://i.stack.imgur.com/lfA3c.png

**Comment by wysaid** [comment]
I'm using xcode 8.0 (the newest version by now)

![http://i.imgur.com/epsCWTm.png](http://i.imgur.com/epsCWTm.png)

**Comment by wysaid** [comment]
Maybe it's fixed, I've added your marker and rebuild the framework~
Please check the code and try again😀

**Comment by starlight173** [comment]
Perfect! Work like charm.
