### ISSUE TITLE
CGEVideoPlayerViewHandler能不能封装一个SaveVideo的接口？

### ISSUE THREAD

**Issue by synwith** [wysaid/ios-gpuimage-plus#14]
貌似目前没有保存视频的功能。

**Comment by wysaid** [comment]
有， Simple Test Cases 里面。
看一下test case就明白了

**Comment by synwith** [comment]
好！非常感谢！

**Comment by synwith** [comment]
已经解决，再次感谢。随带问一下，CGE目前的接口能实现类似行车记录那样，相机右下角一边显示时间（读秒在跳动）一边录制保存视频吗？

**Comment by wysaid** [comment]
当然可以， 自己写滤镜吧， 准备一张资源图， 里面有0-9等数字以及一些标点符号， 按sprite的方式更新渲染就行了。 这个需要你自己去摸索一下。
如果要输出手打任意中文的话稍微麻烦一点， 要结合FreeType之类的第三方来加载字体文件。（或者利用ios/android的原生API输出文字到UIImge或者Bitmap， 然后生成纹理。
方法很多， 你参考吧。

**Comment by synwith** [comment]
谢谢，下来思考思考。现在还不熟悉这个滤镜框架。
