### ISSUE TITLE
Public function

### ISSUE THREAD

**Issue by letien91** [wysaid/ios-gpuimage-plus#17]
Hi. I'm working in face landmark detection. Can you public `AVCaptureDeviceInput *_videoInput;` and `AVCaptureVideoDataOutput *_videoOutput;` in `CGECameraDevice`

**Comment by wysaid** [comment]
The whole repo will be open soon.
 Maybe in a week.

**Comment by letien91** [comment]
Thank you. :)

**Comment by letien91** [comment]
@wysaid : This is the best framework that I have seen 
Thank for your great work. 
Thank you so much :)
