### ISSUE TITLE
Better approach

### ISSUE THREAD

**Issue by NikhilManapure** [wysaid/ios-gpuimage-plus#19]
Should I use GLKView and CGEImageViewHandler to set image and then filters to it or 

Should I use cgeFilterUIImage_MultipleEffects  and set the result image to UIImageView?

Which is better way?

**Comment by wysaid** [comment]
It depends on your requirement.
If you just display the filtered image, and never change it (such as set intensity), you should use the  second one. Or you should use the first one.

**Comment by NikhilManapure** [comment]
Does changing intensity call cgeFilterUIImage_MultipleEffects method again with different intensity or it follows some other approach?

Because if it calls same method then the time taken will be same.

**Comment by NikhilManapure** [comment]
And another issue I have is that if I set an image(which was taken by front camera) to GLKView, the image gets rotated upside down

Do you know why is this happening?

**Comment by wysaid** [comment]
1. 'setIntensity' for the first way is much faster than the second one.
2. Will this happen in the demo?

**Comment by wysaid** [comment]
All source codes are open, maybe you can find your answer by reviewing it.

**Comment by NikhilManapure** [comment]
Yes

I clicked a pic using my app and saved it to gallery and then imported the same pic in your demo app and the image was shown upside down.

**Comment by wysaid** [comment]
I mean, leave your app.
Use the builtin camera or use my demo to take the pic.
If it's OK, the problem is yours.

**Comment by NikhilManapure** [comment]
The problem is mine,
I checked as you said and image got upside down only if the picture was taken by my app's camera.
But can you give me any hints on why is this working this way because I have not done anything different while capturing from front camera. 

Does GLKView read any image metadata and rotates on some condition?

**Comment by wysaid** [comment]
The code is open, you can check the picture taking function, and find the way to solve your problem.
