### ISSUE TITLE
Can you make a CropFilter like GPUImageCropFilter?

### ISSUE THREAD

**Issue by huishuyi** [wysaid/ios-gpuimage-plus#2]
I want to crop the camera to a certain rect ,like the GPUImageCropFilter,I just want my camera to capture a small part of the screen,can you create one smarter friends

**Comment by wysaid** [comment]
If you're scaling the result to the certain rect, just set the viewport to the rect.

If you're really cropping part of the result, you can also just imp it by custom your viewport.
So this func needs no filter. 
e. g. <b>You're capturing with a resolution of "X x Y", but you just want a result of "A x B" of it</b> -- crop align center.
Then the viewport can be glViewport((A-X)/2, (B-Y)/2, X, Y)

**Comment by huishuyi** [comment]
我的iOS程序的GLKView宽度是屏幕宽度，高度和宽度比是16：9，我已经设置了
1.if([_myCameraViewHandler setupCamera: AVCaptureSessionPreset1280x720 cameraPosition:AVCaptureDevicePositionFront isFrontCameraMirrored:YES authorizationFailed:^{
        NSLog(@"未取得相机或者麦克风权限!!");
    }])
2.[_myCameraViewHandler startRecording:_movieURL size:CGSizeMake(1280, 720)];
但是视频录制完成后在图片库中视频框的比例正确但视频内容明显是由全屏拍摄视频挤压形成的，也就是说仅仅设置这两个参数还是无法让摄像机只拍摄屏幕的一部分并保存这一部分，能否只是用iOS语言把这事完成，还是必须要用OpenGL,如果只能使用OpenGL，那应该把代码加在哪里呢？

**Comment by wysaid** [comment]
如果你在使用我的框架， 你只需要设置一个参数, 我的demo里面就有。
CGECameraViewHandler *handler;
///your code of init
[handler fitViewSizeKeepRatio:YES]
这样就不会拉伸了

**Comment by wysaid** [comment]
录像保存应该使用
[_myCameraViewHandler startRecording:_movieURL size:CGSizeMake(720, 1280)];
因为相机的画面是旋转过的

**Comment by huishuyi** [comment]
非常非常感谢您能抽空看我的问题，我是把GLKView设置成了宽大于高的长方形，想要模拟标准摄像镜头的样式，也设置了【_myCameraViewHandler fitViewSizeKeepRatio:YES】，这样GLKView的图像保证了不压缩，而是截取呈现视角的一部分展示，我现在的问题就是。。。我能不能当录制结束后，保存到相册的视频也是这一部分（而不是整个视角的内容，相当于舍弃了部分系统摄像头的拍摄内容，所见即所得），现在我是怎么设置，保存到本地的都是整个摄像头的内容，无法灵活的改变GLKView的形状，从而给用户录制多种模式的视频，1：1，16：9或者4：3等等，真是麻烦你了

**Comment by huishuyi** [comment]
![Uploading IMG_0485.PNG…]()
![Uploading IMG_0484.PNG…]()

**Comment by wysaid** [comment]
可以， 后面我会直接在录制接口中加入这个功能， 无需所谓 cropfilter

**Comment by huishuyi** [comment]
千言万语只有感激和佩服，我人在上海，有机会真的想找大神交流一下

发自我的 iPhone

**Comment by wysaid** [comment]
已经加上去了, 在相机那个测试用例里面， 下方菜单多了一个按钮， 裁剪录制

**Comment by huishuyi** [comment]
非常非常感谢你，我今后有什么技术突破也会分享给大家，延续互联网精神，感动！感谢！感激！

发自我的 iPhone

**Comment by wysaid** [comment]
👍

**Comment by AKin28** [comment]
GPUImage录制视频后（预览是正方形的）截成正方形，是怎么做到的？  用普通的相机录制视频，用AVMutableVideoCompositionInstruction这一系列的能截成正方形。GPUImage录制的视频就不行，会出现上半部分是黑色的情况

**Comment by AKin28** [comment]
同一个方法，面对不同方式录制的视频，出现了不同的效果，真不知道该如何是好了。感谢你是否能给予解答。。。

**Comment by wysaid** [comment]
@AKin28  composition 这个， 苹果的接口本身有些诡异的错误，就我经验而言， AVFileTypeMPEG4与AVFileTypeQuickTimeMovie 有较大的区别， 不可两者拿来composition,  否则会出现莫名错误
AVFileTypeQuickTimeMovie 做出来的composition在apple设备上运行良好， 但是如果要导出到其他设备， 最好用AVFileTypeMPEG4。

**Comment by AKin28** [comment]
用GPU录制了两秒的视频，截成正方形那个问题解决了，
我感觉是因为GPUImage的movieWrite写入时的尺寸和系统相机是颠倒的，我在截取正方形时给AVMutableVideoCompositionLayerInstruction下的有个矩阵参赛修改了，就解决了。

现在遇到压缩问题。。。。
movieWrite是 720＊1280，两秒大概1.4MB
AVAssetExportPresetLowQuality  
AVAssetExportPresetMediumQuality  
AVAssetExportPresetHighestQuality
导出时用的medium，变成了200KB左右的样子，达不到预期效果
用highest 质量又太大，
用AVAssetExportPreset640x480，质量基本没变化，但是视频模糊了。
请问，有好的压缩方式吗？既保证两秒视频看着像样，又能在500KB以下。。。
谢谢

**Comment by wysaid** [comment]
720P的话， 你直接录制完， 啥都不干， 基本都在500k以下的, 清晰度也高, 为啥非要export
