### ISSUE TITLE
while adding both CGE and openCV to project

### ISSUE THREAD

**Issue by NikhilManapure** [wysaid/ios-gpuimage-plus#20]
i did

  pod 'OpenCV'
  pod 'libCGE', :git => 'https://github.com/wysaid/ios-gpuimage-plus-pod.git', :tag => '2.4.3'

and its giving me bunch of linker errors.
Any hints?

**Comment by wysaid** [comment]
So what is the error?

**Comment by NikhilManapure** [comment]
![screen shot 2017-06-20 at 2 05 15 pm](https://user-images.githubusercontent.com/5690565/27324065-8932e7de-55c1-11e7-9d4a-67bd3a6afb29.png)


This is even before importing opencv2. Until now I have just did pod install.

**Comment by wysaid** [comment]
Add 'ImageIO.framework' to your project.

**Comment by NikhilManapure** [comment]
![screen shot 2017-06-20 at 2 12 14 pm](https://user-images.githubusercontent.com/5690565/27324335-86cd87f0-55c2-11e7-8160-a6824161ad1c.png)

Now getting this as error.

**Comment by wysaid** [comment]
>Add MobileCoreServices.framework

Just google the error next time, and the problem will be solved soon.
