### ISSUE TITLE
cge.h 头文件中, 有几个文件不存在

### ISSUE THREAD

**Issue by Zeta-XL** [wysaid/ios-gpuimage-plus#21]
反馈个问题, 下面几个滤镜在 打包好的 cge.framework 中找不到, 会引起报错
#import <cge/cgeAlienLookFilter.h>
#import <cge/cgeDistortionFilter.h>
#import <cge/cgeEnlargeEyeFilter.h>
#import <cge/cgeMarscaraFilter.h>
#import <cge/cgeMultipleEffectsDataset.h>
我在源码里搜索了一遍, 也没找到. 希望后续更新的时候, 老大给处理一下

**Comment by wysaid** [comment]
好的， 删掉就行， 这些暂时没什么用

**Comment by wysaid** [comment]
好的， 删掉就行， 这些暂时没什么用

**Comment by Zeta-XL** [comment]
赞👍
