### ISSUE TITLE
How to apply multiple filters at a time to CGEImageViewHandler?

### ISSUE THREAD

**Issue by NikhilManapure** [wysaid/ios-gpuimage-plus#27]
setFilterWithConfig is known to me, which can apply the single filter at a time, please help for putting multiple filters at a time.

**Comment by wysaid** [comment]
Just combine the config string.

**Comment by NikhilManapure** [comment]
ok.

If I want to use two filters like cgeBrightnessAdjust and cgeExposureAdjust (Classes) together and then set their intensities independently, how would that be?

**Comment by wysaid** [comment]
Use `.mm` file extension for your source code.
Import <cge/cge.h>
and follow this:
>1.Create a `CGEMultipleEffectsFilter` (Please find the init function of this class in the source)
>2.Create the two filter  `cgeBrightnessAdjust` and `cgeExposureAdjust ` (Keep the instance as filterA and filterB)
>3. Add the two filters to the `CGEMultipleEffectsFilter`
>4. Add `CGEMultipleEffectsFilter` to the `ImageHandler` such as [cgeImageViewHandler](https://github.com/wysaid/ios-gpuimage-plus/blob/master/library/cge/interfaces/cgeImageViewHandler.h#L40)
>5. Call `filterA->setIntensity` or `filterB->setIntensity` as you like. (Remember to join the queue of the gl context)

**Comment by wysaid** [comment]
And don't forget to call [the flush function](https://github.com/wysaid/ios-gpuimage-plus/blob/master/library/cge/interfaces/cgeImageViewHandler.h#L43)

**Comment by NikhilManapure** [comment]
Fine bro, I will try and ask you if I have some doubt.

Thanks :)

**Comment by anu30** [comment]
Hi Wysaid,

I am creating CGEMultipleEffectsFilter as you said for multiple filters. You mentioned the init function is in the source. Can you please provide me link for the same?
