### ISSUE TITLE
[BUG] bufferRequestRGBA doesn't show the point

### ISSUE THREAD

**Issue by letien91** [wysaid/ios-gpuimage-plus#29]
Hi. Thanks for your project.
I ran the demo_ios_11. It worked for iPhone 6 and above. It crashed in iPhone 4/4s/5/5s.
When I change `bufferRequestRGBA` from `No` to `Yes`. The camera with face landmark doesn't show anything.
Can you fix it?
Thanks.

**Comment by wysaid** [comment]
- Aha, the device below 5s can upgrade to ios11?
- And to use rgba data, you should change `kCGImagePropertyOrientationRight` to orientation-up, but this way is much slower.

**Comment by letien91** [comment]
Thanks for your reply 
- I have a device iPhone 5s and it is iOS 11.0
- I have just changed the `kCGImagePropertyOrientationRight` to `kCGImagePropertyOrientationUp`. But I don't see anything change. 
Do I make any mistake?
```
- (BOOL)processingHandleBuffer: (CVImageBufferRef)imageBuffer
{
    CGImagePropertyOrientation orientation = kCGImagePropertyOrientationUp;
    
    if(!_forceDetectAsync) {
        [_faceLandMarkHandler performRequests:_faceLandMarkRequests onCVPixelBuffer:imageBuffer orientation:orientation error:nil];
    }
    
    else if(dispatch_semaphore_wait(_faceDetectSema, DISPATCH_TIME_NOW) == 0) {
        CFRetain(imageBuffer);
        dispatch_async(dispatch_get_main_queue(), ^{
            [_faceLandMarkHandler performRequests:_faceLandMarkRequests onCVPixelBuffer:imageBuffer orientation:orientation error:nil];
            CFRelease(imageBuffer);
            dispatch_semaphore_signal(_faceDetectSema);
        });
    }
    
    return NO;
}
```

**Comment by wysaid** [comment]
It's a bug of the library.
`return YES` at last may fix that.
I'll push a fix for that
