### ISSUE TITLE
can't use enableGlobalFilter

### ISSUE THREAD

**Issue by jinookkoo** [wysaid/ios-gpuimage-plus#31]
@adjust lut texture_file.png
@krblend ol texture_file.png

If I use enableGlobalFilter with above config, The error occur.

❌❌❌
Load texture texture_file.png failed!

❌❌❌
blend - ol : loadResources failed: texture_file.png

The loadImageCallback doesn't called.

**Comment by wysaid** [comment]
Can you give me a fork with the problem?

**Comment by jinookkoo** [comment]
Here's example.

https://github.com/eyu0415/ios-gpuimage-plus/commit/b078a03199e7d19ebe6de796d976d18ed481ea65

**Comment by wysaid** [comment]
👍
