### ISSUE TITLE
Filter preview : Enhancement

### ISSUE THREAD

**Issue by hcrgithub** [wysaid/ios-gpuimage-plus#34]
Thanks for making such a good library.

I've an enhancement suggestion to show preview of filter as shown here http://prntscr.com/hc0kkk

Regards,
Hooda

**Comment by hcrgithub** [comment]
Can you please recommend the steps to follow to show filter preview?

**Comment by wysaid** [comment]
It looks like a simple LUT filter.
![lut_origin](https://user-images.githubusercontent.com/1430725/33000270-02242fc0-cde2-11e7-8fa6-b1b4edd56ae4.png)

- Import the origin lut image to that app, do the filter, and save as `lut.png`
- Put the `lut.pnt` to the right place and run filter rule `@adjust lut lut.png`

**Comment by wysaid** [comment]
The image above is the `origin lut image`
