### ISSUE TITLE
大佬，请问如何将源码导入工程，有什么特殊配置么?

### ISSUE THREAD

**Issue by indulgeIn** [wysaid/ios-gpuimage-plus#36]
我这边尝试了，NSRuntime、NSCopy之类会有报错

**Comment by wysaid** [comment]
代码里面有个文件叫 `libCGE-prefix.pch`
把这个文件里面的东西加到你的项目的 prefix header 就行了。
或者直接引用library目录下的静态库工程。

**Comment by indulgeIn** [comment]
直接导入项目把全局文件修改了，还是会报错。我直接用的引用工程

**Comment by wysaid** [comment]
有的头文件必须要c++才能引用。 如果你加了， 记得把文件后缀名改为 .mm

**Comment by wysaid** [comment]
报错的那个文件改后缀名就行了。
带有c++ 的头文件都在 静态库工程的 native 的group里面

**Comment by indulgeIn** [comment]
哦哦，谢过，我去试试
