### ISSUE TITLE
Warning: Umbrella header for module 'cge' does not include header on Swift using Cocoapod

### ISSUE THREAD

**Issue by starlight173** [wysaid/ios-gpuimage-plus#37]
![screen shot 2018-01-24 at 10 52 54](https://user-images.githubusercontent.com/10140561/35313781-e4b7d3ba-00f4-11e8-9404-211f5295a151.png)

**Comment by wysaid** [comment]
I see.
The [umbrella header](https://github.com/wysaid/ios-gpuimage-plus/blob/master/library/cge/include/cge.h) has checked the `__OBJC__ ` macro
Maybe you should change the line 32 to 
```
#if defined(__OBJC__) || defined(THE_MACRO_TO_DETERMINE_IF_YOURE_USING_SWIFT)
```

**Comment by starlight173** [comment]
Yes, thanks for your tips. If you have time, could you update the Cocoapoad version?

**Comment by wysaid** [comment]
Sure

**Comment by wysaid** [comment]
@gloryluu 
What is the macro you used?
I'm not familiar with swift, and I can't find any macro like `__OBJC__`.

**Comment by wysaid** [comment]
@gloryluu 
I've tried search a lot, but no such answer. 😰

**Comment by starlight173** [comment]
I just updated to the latest Cocoapod and the warning's gone. 
You can close it now. Thank you.
