### ISSUE TITLE
cross filter effect

### ISSUE THREAD

**Issue by alyfreym** [wysaid/ios-gpuimage-plus#38]
Hello, I wanted to ask how to implement this library cross filter effects 
![htb1nqm4rfxxxxxlxfxxq6xxfxxxa](https://user-images.githubusercontent.com/29518174/36249453-965e2f2e-125c-11e8-95e5-2d8c22ae7837.jpg). Please, if this library can not do this, tell me how to do it in IOS. Any references, lessons I will be grateful for. Thanks. PS - Sorry for my English:)

**Comment by wysaid** [comment]
It is not provided by default. You should try to implement it by yourself. (Write a custom filter by your self.)
You may need to calc the average luminance of the picture, and do some blurring with special thresholds.

**Comment by alyfreym** [comment]
Well, thanks, I'll try.
