### ISSUE TITLE
iphone 6 OS- 11.2.5 camera is not supporting.

### ISSUE THREAD

**Issue by Rahulclaritaz** [wysaid/ios-gpuimage-plus#39]
Hi wysaid,
    I am facing the issue, if i run the code with iphone 6 - OS- 11.2.5 then Camera is not supporting, after 3 second camera used to stuck, but if i choose any other device with same OS it is working fine. out of 3 iphone 6 , 2 iphone not supporting, other all the device is working. please help me out this issue.

**Comment by wysaid** [comment]
Hi, did this happen on your app or the builtin demo?
If it's happening in the demo, please show me the log.

**Comment by Rahulclaritaz** [comment]
Hi wysaid, 
  Thanks for response. as off now it is not reproducible , if again got then i will send with the log.
  thanks
