### ISSUE TITLE
CGEShared Context Release Error

### ISSUE THREAD

**Issue by jhrasco** [wysaid/ios-gpuimage-plus#41]
What could be the possible cause for the error logs below? Will there be an issue if the applying of filter is done in the background thread?

```
2018-06-01 19:45:14.003100+0800 My App[24542:539209] CGEShared Context release...

❌❌❌
Image Handler initImageFBO failed! 8219

❌❌❌
/Users/yangwang/work/git/ios-gpuimage-plus/library/cge/src/common/cgeImageHandler.cpp:105

❌❌❌
Init handler failed!!!!

❌❌❌
/Users/yangwang/work/git/ios-gpuimage-plus/library/cge/interfaces/cgeUtilFunctions.mm:144
2018-06-01 19:45:14.007896+0800 My App[24542:539374] CGEShared Context release...
```

Thank you.

**Comment by wysaid** [comment]
Please give me a fork which can produce this error, so I can see the error.

**Comment by jhrasco** [comment]
Hi @wysaid. Thank you for your response. I have created a simple project that you can access here: https://github.com/jhrasco/CGEImageFilter

In viewDidLoad, the app performs filter processes in the background thread and returns to the main thread. You can see in the logs that "CGEShared Context release..." messages are printed. Also, there is a chance that you will encounter exc_bad_access if you run the app multiple times.

Hoping for your response. Thank you.

**Comment by wysaid** [comment]
The demo is all right.
I can see the filters applied. 
`CGEShared Context release...`  is just a  normal log message, you can compile the library yourself and remove the useless log msg.

**Comment by jhrasco** [comment]
Hi @wysaid. Thank you for your response. Your response is very much appreciated. 

If that’s the case, then it is fine. I think the major problem would be the crash when performing it in the background thread. Did you get a chance to replicate the crash? You run the app multiple times to reproduce the crash. 

Let me know if you replicated it. Thank you.

**Comment by wysaid** [comment]
I've tried a few times, and nothing happened.

**Comment by jhrasco** [comment]
Hmm. That’s weird. I can constantly replicate it. It crashes I think once every 10 runs. Anyway, thanks.

**Comment by wysaid** [comment]
I see, your code is wrong. Please see this: https://github.com/wysaid/ios-gpuimage-plus/blob/master/library/cge/interfaces/cgeUtilFunctions.h#L70

When you use that function in different threads, you should create a CGESharedGLContext for each thread.

**Comment by jhrasco** [comment]
Oh. Sorry. My bad. I overlooked the documentation. Thank you for your help @wysaid. Very much appreciated. Thanks.
