### ISSUE TITLE
Player Demo能不能将预览到的滤镜效果另存为到本地一份

### ISSUE THREAD

**Issue by huishuyi** [wysaid/ios-gpuimage-plus#7]
现在我可以选择滤镜浏览美化后的效果，到不知道将效果怎么保存到本地，作为一个新文件生成

**Comment by MyOnlyOnlySunshine** [comment]
请问你导入这个框架 包含头文件的时候 有没有报错啊  为什么我到不进来  编译时候一直报错 头文件找不到 昨天搞了一天了 求指教啊

**Comment by huishuyi** [comment]
Build Settings里面搜索Search Paths,将cge.framework下面的Header文件路径拖到User Header Search Paths里面，就好了，赶紧试试

**Comment by huishuyi** [comment]
我说的，那个问题你知道吗？如何将本地视频添加滤镜之后，重新在保存，就像保存处理过的图片一样？

**Comment by wysaid** [comment]
SimpleTestCase里面的 “离屏渲染滤镜” 测试用例
CGEVideoFrameRecorder 下的 generateVideoWithFilter 方法
这些问题就在demo里面， 请仔细观察
