### ISSUE TITLE
videoFrameRecorder 生成带滤镜的视频generateVideoWithFilter方法，能不能不压缩或者是AVAssetExportPresetHighestQuality

### ISSUE THREAD

**Issue by huishuyi** [wysaid/ios-gpuimage-plus#8]
给本地视频添加滤镜重新生成后，发现视频压缩选择了medium,有些影响质量，能不能保证质量的前提下加滤镜，master

**Comment by wysaid** [comment]
这个质量是你自己设定的
videoReadingComplete 这个delegate里面 endRecording 末尾有个 compress level
问这种问题之前请好好看看代码哦， 不要盲目提问
